version: "3"

services:
  api:
    build: .
    depends_on:
      - mongo
    environment:
      - PORT=5000
      - MONGO_URL=mongodb://mongo:27017/test
      - APPLICATION_NAME=Share Your Idea
      - JWT_SECRET=NODE_YEIZER
      - CACHE_KEY=MyStrongPasswordCache
      - SWAGGER_DOC=swaggerPROD
    ports:
      - "5000:5000"
    
  mongo:
    image: mongo